#!/bin/bash
set -euo pipefail

# Get the location of this script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Prefer the python version of Ophis, but fall back on the Windows exe
OPHIS_PYTHON_CMD=${SCRIPT_DIR}/unix/bin/ophis
OPHIS_WINDOWS_CMD=${SCRIPT_DIR}/windows/ophis.exe

if ophis_version=$(${OPHIS_PYTHON_CMD} --version 2>/dev/null); then
    exec ${OPHIS_PYTHON_CMD} $1 -o $2
else
    exec ${OPHIS_WINDOWS_CMD} $1 $2
fi
